#!/usr/bin/env bash
# bash: script to display information about subdomains `DNS` records

dig_dns_info (){
    dig +noall +answer "$1" | 
        awk '
        {split($1,a,"."); 
        printf "The subdomain %s is a %s record and points to %s\n", a[1], $4, $5 }
        '
}

if [ "$#" -eq 1 ];
then
    dig_dns_info "www.$1"
    dig_dns_info "lb-01.$1"
    dig_dns_info "web-01.$1"
    dig_dns_info "web-02.$1"
elif [ "$#" -eq 2 ];
then
    dig_dns_info "$2.$1"
fi
