#!/usr/bin/env bash
# script creates file with PID, and acts based off signal handlers

trap 'echo "I hate the kill command" && rm /var/run/myscript.pid && exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid && exit' SIGQUIT

# create pid file with PID
echo $$ > /var/run/myscript.pid

while true; do
  echo "To infinity and beyond"
  sleep 2
done
