#!/usr/bin/env bash
# FizzBuzz: script that displays numbers from 1 thro' 100

for i in $(seq 1 100); do
    if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
