#!/usr/bin/env bash
# configure ufw - blocks all ingress, except these TCP ports:
#	22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo apt-get update -y
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
echo "yes" | sudo ufw enable
sudo ufw status
