#!/usr/bin/env bash
# this script runs the "whoami" command under the user passed as an argument:
if [ -z "$1" ]; then
  echo "Usage: $0 <username>"
  exit 1
fi
if [ $# -eq 1 ]; then
  sudo -u "$1" "whoami"
fi
# sudo -u "$1" whoami # -c "whoami"
